# docker-compose.yml
version: '3.8'
services:
  myapp:
    image: "myapp:v1"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
      
    # You should copy volumes from container before mounting them!
    # docker cp CONTAINER_ID:/app/server/data/ ./volumes/data/
    # docker cp CONTAINER_ID:/app/server/html/ ./volumes/html/

    # volumes:
      # - ./volumes/data/:/app/server/data/
      # - ./volumes/html/:/app/server/html/

# networks:
#   default:
#     external:
#       name: main
