export declare const APP_NAME: string;
export declare const USE_PWA: boolean;
export declare const USE_SPA: boolean;
export declare const DEV_FRONTEND_PORT: number;
export declare const DEV_SERVER_PORT: number;
export declare const MAX_UPLOAD_FILE_SIZE: number;
export declare const COOKIE_NAME: string;
export declare const USE_SOCKET: boolean;
export declare const CHII_PORT: number;
