# docker-compose.yml
version: '3.8'
services:
  myapp:
    container_name: myapp
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./volumes/data:/app/data
      - ./volumes/resources:/app/html/resources
    # ports:
    #   - 3000:3000
# networks:
#   default:
#     name: main
