# docker-compose.yml
version: '3.8'
services:
  myapp:
    container_name: myapp
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./volumes/uploads:/app/html/resources/uploads
      - ./volumes/db:/app/data/db
    # ports:
    #   - 3000:3000
# networks:
#   default:
#     name: main
